config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users

  root :to => redirect('/admin')
  get 'admin' => 'admin#dashboard'
  get 'admin/app_selection/:app_id' => 'admin#app_selection'
  get 'admin/statistics' => 'admin#statistics'
  get 'admin/live_view' => 'admin#live_view'
  get 'admin/api_endpoints' => 'admin#api_endpoints'
  post 'admin/ordered_view_fields/:id/reorder_fields' => 'admin/ordered_view_fields#reorder_fields'
  get 'admin/ordered_view_fields/:id/show_field' => 'admin/ordered_view_fields#show_field', as: :show_field
  get 'admin/ordered_view_fields/:id/hide_field' => 'admin/ordered_view_fields#hide_field', as: :hide_field

  DynamicAdminRouter.load

  namespace :api do
    namespace :v1 do
      resources :apps, only: [:show]
      scope "/:app_id" do
        resources :articles, only: [:index]
        resources :pages, only: [:index]
        resources :videos, only: [:index]
        resources :maps, only: [:index]      
        resources :competitions, only: [:index]
        resources :user_feedbacks, only: [:create]
        resources :schedules, only: [:index, :show]
        resources :galleries, only: [:index]    
        resources :maps, only: [:index]
      end
    end
  end

end

app/models/ordered_view_field.rb
# == Schema Information
#
# Table name: ordered_view_fields
#
#  id            :integer          not null, primary key
#  name_of_model :string
#  name_of_view  :string
#  model_fields  :text             default([])
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class OrderedViewField < ActiveRecord::Base

  serialize :model_fields, Array

end

app/controllers/admin/ordered_view_fields_controller.rb
class Admin::OrderedViewFieldsController < AdminController
  
  layout 'admin'
  before_action :set_ordered_view_field, only: [:show, :edit, :update, :destroy, :reorder_fields, :show_field, :hide_field]


  def index
    @ordered_view_fields = OrderedViewField.all
  end

  def reorder_fields

    @ordered_view_field.model_fields.clear()
    params[:order].each do |field|
      @ordered_view_field.model_fields << field
    end 
    @ordered_view_field.save

  end

  def hide_field
    @ordered_view_field.model_fields.delete(params[:field])
    @ordered_view_field.save
    redirect_to :back
  end

  def show_field
    @ordered_view_field.model_fields << params[:field]
    @ordered_view_field.save
    redirect_to :back
  end

  def destroy
    @ordered_view_field.destroy
    respond_to do |format|
      format.html { redirect_to admin_ordered_view_fields_url, notice: 'OrderedViewField was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_ordered_view_field
      @ordered_view_field = OrderedViewField.find(params[:id])
    end

end

app/views/admin/ordered_view_fields/edit.html.erb
<% content_for :content do %>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Field</th>
        <th>Show/Hide</th>
      </tr>
    </thead>

    <tbody class="sortable">
      <% @ordered_view_field.model_fields.each do |field| %>
        <tr class="model-field" data-id="<%= field %>">
          <td><%= field %></td>
          <td><%= link_to 'HIDE', hide_field_path(field: field) %></td>
        </tr>
      <% end %>
    </tbody>
    
    <tbody>
      <% (@ordered_view_field.name_of_model.constantize.column_names - @ordered_view_field.model_fields).each do |field| %>
        <tr class="model-field" data-id="<%= field %>">
          <td><%= field %></td>
          <td><%= link_to 'SHOW', show_field_path(field: field) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <script>
    $(function(){
      $('.sortable').sortable().bind('sortupdate', function() {
        updated_order = [];
        $('.model-field').each(function(){
            updated_order.push($(this).data("id"));
        });
        $.ajax({
            type: "POST",
            url: '/admin/ordered_view_fields/<%= @ordered_view_field.id %>/reorder_fields',
            data: { order: updated_order }
        });
      }); 
    });
  </script>

<% end %>

app/views/admin/ordered_view_fields/index.html.erb
<% content_for :content do %>
<div class="box box-<%= bootstrap_style %>">
  <div class="box-header with-border">
    <div class="col-md-10">
      <h3 class="box-title" style="margin-top:10px;"> <%= controller_name.capitalize %></h3>  
    </div>
    <div class="col-md-2">
      <%= link_to("New #{controller_name.singularize.capitalize}", "new_admin_#{controller_name.singularize.downcase}".to_sym, class: "btn btn-#{bootstrap_style}") %>
    </div>
  </div>
  <div class="box-body">
    <div class="col-md-12">
      <div class="box box-<%= bootstrap_style %> box-solid">
        <div class="box-header">
          <h3 class="box-title">Index</h3>
        </div>
        <div class="box-body">
          <table id="item" class="table table-bordered table-striped">
            <thead>
            <tr>
              <% (controller_name.singularize.classify.constantize.column_names - ["id", "created_at", "updated_at"]).each do |field| %>
                  <th style="max-width:120px;"><%= field.humanize.capitalize %></th>
              <% end %>
              <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <% eval("@#{controller_name}").each do |item| %>
                <tr>
                  <% (controller_name.singularize.classify.constantize.column_names - ["id", "created_at", "updated_at"]).each do |field| %>
                    <td>
                      <% type = controller_name.singularize.classify.constantize.column_for_attribute(field).type %>

                      <% if field.include? 'image' and !field.include? 'caption' %>
                        <%= image_tag(item.send(field).url(:thumb), :size=>"60x60") unless item.send(field).url.nil?%>
                      
                      <% elsif type == :string or type == :text or type == :boolean %>
                        <%= item.send(field) %>
                          
                      <% elsif field == 'app_id' %>
                        <%= item.app.try(:name) %>

                      <% elsif field == 'company_id' %>
                        <%= item.company.try(:name) %>

                      <% elsif type == :datetime %>
                        <%= item.send(field).strftime("%d %b, %Y") %>  
                      
                      <% end %>
                    </td>
                  <% end %> 
                  <td class="vert-align" style="width:160px;">
                    <%= link_to(eval("admin_#{controller_name.singularize.downcase}_path(item)"), :title=>"INFO", class: "btn btn-default index-action-button-show") do %>
                      <i class="index-action-button fa fa-info-circle"></i>
                    <% end %>
                    <%= link_to(eval("edit_admin_#{controller_name.singularize.downcase}_path(item)"), :title=>"EDIT", class: "btn btn-default index-action-button-edit") do %>
                      <i class="index-action-button  fa fa-pencil-square"></i>
                    <% end %>              
                    <%= link_to("/admin/#{controller_name.downcase}/#{item.id}", :method => :delete, data: {confirm: 'Are you sure you want to delete this record?'}, :title=>"DELETE", class: "btn btn-default index-action-button-delete") do %>
                      <i class="index-action-button  fa fa-remove"></i>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#item").dataTable({
          
        });
    });
</script>

<% end %>