config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users

  root :to => redirect('/admin')
  get 'admin' => 'admin#dashboard'
  get 'admin/app_selection/:app_id' => 'admin#app_selection'
  get 'admin/statistics' => 'admin#statistics'
  get 'admin/live_view' => 'admin#live_view'
  get 'admin/api_endpoints' => 'admin#api_endpoints'
  post 'admin/ordered_view_fields/:id/reorder_fields' => 'admin/ordered_view_fields#reorder_fields'
  get 'admin/ordered_view_fields/:id/show_field' => 'admin/ordered_view_fields#show_field', as: :show_field
  get 'admin/ordered_view_fields/:id/hide_field' => 'admin/ordered_view_fields#hide_field', as: :hide_field

  DynamicAdminRouter.load

  namespace :api do
    namespace :v1 do
      resources :apps, only: [:show]
      scope "/:app_id" do
        resources :articles, only: [:index]
        resources :pages, only: [:index]
        resources :videos, only: [:index]
        resources :maps, only: [:index]      
        resources :competitions, only: [:index]
        resources :user_feedbacks, only: [:create]
        resources :schedules, only: [:index, :show]
        resources :galleries, only: [:index]    
        resources :maps, only: [:index]
      end
    end
  end

end

app/views/layouts/_header.html.erb
<header class="main-header">

  <a href="/" class="logo">
    <span class="logo-mini"><b>L</b>M</span>
    <span class="logo-lg"><b><%= @company_layout.name.upcase %></b>Mobile
    </span>
  </a>

  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- TODO: Apps shown should be those assigned/owned-by User -->
    <% if current_user.superadmin? %>
      <div class="navbar-custom-menu" style="float:left">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="/assets/admin/mobile_3.png" class="user-image" style="margin-left:10px; height:30px; width:30px"/>
              <span class="hidden-xs" style="font-size:18px;"><%= @app.present? ? @app.name : "Showing All Apps" %></span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header" style="height:100px;">
                <p>App Selection Menu</p>
                <select class="form-control" onChange="if(this.selectedIndex!=0) self.location= options[this.selectedIndex].value">
                  <option value=admin>Select App</option>
                  <option value=<%=root_url %>admin/app_selection/0>All Apps</option>
                  <% App.all.each do |app| %>
                    <option value=<%=root_url %>admin/app_selection/<%=app.id %>><%= app.name %></option>
                  <% end %>
                </select>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    <% end %>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="/assets/admin/lumico_user.png" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.full_name %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="/assets/admin/lumico_user.png" class="img-circle" alt="User Image" />
              <p>
                <%= current_user.full_name %><br>
                <%= current_user.role %>
                <small>Active since  <%= current_user.created_at.strftime("%B %Y") %></small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-12 text-center">
                <p><%= current_user.email %></p>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to 'Edit Profile', edit_admin_user_path(current_user), class: 'btn btn-default btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar">

  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= eval("#{logo_image}" + ", :class=>'img-circle'") %>
        <!-- <img src="/assets/admin/kknk_icon.png" class="img-circle" alt="User Image" /> -->
      </div>
      <div class="pull-left info">  
        <p> User Role:</p>
        <p><%= current_user.role %></p>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li class="header" style="text-align:center">MAIN NAVIGATION</li>
      <% if current_user.admin? %>
        <li class="treeview">
          <a href="#"><i class='fa fa-link'></i> <span>Administration</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><a href="/admin/users"><i class="fa fa-user-circle-o"></i> Users</a></li>
            <li><a href="/admin/companies"><i class="fa fa-handshake-o"></i> Companies</a></li>
            <li><a href="/admin/ordered_view_fields"><i class="fa fa-list-ol"></i> Order Fields</a></li>
          </ul>
        </li>        
      <% end %>
       <li class="treeview">
        <a href="#"><i class='fa fa-link'></i> <span>App Management</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="/admin/apps"><i class="fa fa-apple"></i> Apps</a></li>
          <li><a href="/admin/articles"><i class="fa fa-newspaper-o"></i> Articles</a></li>
          <li><a href="/admin/pages"><i class="fa fa-book"></i> Pages</a></li>
          <li><a href="/admin/videos"><i class="fa fa-video-camera"></i> Videos</a></li>
          <li><a href="#"><i class="fa fa-photo"></i> Galleries</a></li>
          <li><a href="/admin/competitions"><i class="fa fa-trophy"></i> Competitions</a></li>
          <li><a href="/admin/schedules"><i class="fa fa-calendar"></i> Schedules</a></li>
          <li><a href="#"><i class="fa fa-map-o"></i> Maps</a></li>
          <li><a href="#"><i class="fa fa-envelope"></i> Feedback</a></li>
        </ul>
      </li>
      <li>
        <a href="/admin/api_endpoints"><i class="fa fa-list-alt"></i>JSON Output</a>
      </li> 
      <li>
        <a href="/admin/live_view"><i class="fa fa-line-chart"></i> Live View</a>
      </li>
    </ul>
  </section>
</aside>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <meta charset="UTF-8">
    <title>Example | API </title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <%# unless Rails.env.development? %>  <!-- WHY GOD -->
      <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->
      <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <%# end %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  
  </head>

  <body class="skin-<%= layout_skin %> sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  
    <div class="wrapper">
      <%= render partial: 'layouts/header' %>
      <%= render partial: 'layouts/sidebar' %>
      <div class="content-wrapper">
        <section class="content-header">
          <h1><%= yield :title %></h1>
        </section>
        <section class="content">
          <% if notice %>
            <div class="alert alert-info alert-dismissable">
              <i class="fa fa-check"></i>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <b><%= notice %></b>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-danger alert-dismissable">
              <i class="fa fa-ban"></i>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <b><%= alert %></b>
            </div>
          <% end %>
          <%= yield :content %>  
        </section>
      </div>
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <%= @app.try(:company).try(:name) %>
        </div>
        <strong>Example &copy; 2017 </strong> All rights reserved.
      </footer>
      <aside class="control-sidebar control-sidebar-dark">
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-sticky-note-o"></i></a></li>
          <li class=""><a href="#control-sidebar-settings-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-pencil-square-o"></i></a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">My Notes (coming soon)</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-thumbs-up bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Update schedule.</h4>
                    <p>Do before 23rd of April</p>
                  </div>
                </a>
              </li>
            </ul>
          </div>
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">New Note (coming soon)</h3>
                <div class="form-group">
                </div>
            </form>
          </div>
        </div>
      </aside>
      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :javascript %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile API</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>API Example</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

</head>
  <body class="hold-transition <%= controller_name %>">
    <div class="wrapper">

          <%= yield %>

    </div>




  </body>
</html>